In [3]:
# 1.import numpy library as np:
import numpy as np
arr=np.array([1,2,3,4])
print("array is",arr)

arr1=np.arange(12)
print(arr1)

array is [1 2 3 4]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [10]:
# 2. convert the given list to a numpy array:
import numpy as np
lst=[1,2,3,4,7,9]
arr=np.array(lst)
print("list:",lst)
print("array:",arr)      

list: [1, 2, 3, 4, 7, 9]
array: [1 2 3 4 7 9]


In [17]:
#3.create an array with five 1's:
x=np.array([1.,1.,1.,1.,1.,])
x

array([1., 1., 1., 1., 1.])

In [29]:
# 4. create an array of size 2x3 with 1's(s rows,2 columns)and assign it to a variable:
array_2x3=np.ones((2,3))
print(array_2x3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# 4(a). using the variable you have created,change the datatype of the array to int

In [31]:
array_2x3_int=array_2x3.astype(int)
print(array_2x3_int)

[[1 1 1 1]
 [1 1 1 1]]


In [23]:
#5. create an array of size 3x3 with 4's on he diagonal:
import numpy as np
array=np.diag([4.,4.,4.])
print(array)
print('--'*15)
k=np.eye(3,3)
print(k)
print('--'*15)
np.fill_diagonal(k,4)
print(k)

[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]
------------------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
------------------------------
[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]


In [27]:
#6.create an array from 0 upto 10(10not inculded):
array=np.arange(0,10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [29]:
#6(a) create an array in range from 12 to 26 using every second number:
#start valur 12
#end value 26 
array=list(range(12,26,2))
print(array)

[12, 14, 16, 18, 20, 22, 24]


In [31]:
#7. create an array between 2 and 4 with 8 equal spaces:
start = 2
end = 4
array=np.linspace(start,end,9)
print(array)

[2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.  ]


In [41]:
#8,9.imort random module from numpy as rd:
import numpy.random as rd
from numpy import random
array=random.choice([1,2,3,4,5])
print(array)

3


In [59]:
#10. create a random array of size 3x5 with values between 0-10:
array=random.choice([2,4,6,8],size=(3,5))
 print(array)

[[8 2 6 2 8]
 [8 6 6 4 4]
 [6 6 4 2 8]]


In [3]:
#11. take square of the array we have just created in no .10:
import numpy as np
array=np.diag([4,4,4])
squared_array=array**2
print(squared_array)

[[16  0  0]
 [ 0 16  0]
 [ 0  0 16]]


SyntaxError: invalid syntax (1660840878.py, line 2)